### ISSUE TITLE
Failing XML test report scan while using bolt protocol

### ISSUE THREAD

**Issue by feststelltaste** [jQAssistant/jqa-xml-plugin#5]
**Problem**  
Exception during Surefire XML test report scan while communicating via the bolt protocol.

**Steps to reproduce**
* Check out https://github.com/buschmais/spring-petclinic
* Uncomment the bolt connection properties in the `pom.xml`
* Start an appropriate Neo4j server (starting the embedded Neo4j server is enough)
* Build the whole project with `mvn clean install`

**Environment**
* Windows 10 64-Bit
* Git Bash
* Java JDK 8 u131
* Maven 3.5.0

**Notes**
* This only occurs while using the bolt protocol. There are no problems while communicating with the embedded Neo4j instance directly.
* Maybe the evaluated new line of the property `line.separator` in the Surefire XML report causes the trouble:
```
    <property name="line.separator" value="
"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
```

**Current workaround**
* Scan succeeds with `-DskipTests`

**Maven debug log snippet**
```
[[1;34mINFO[m] Entering C:/Temp/spring-petclinic/target/surefire-reports
[[1;36mDEBUG[m] Scanning /org.springframework.samples.petclinic.model.ValidatorTests.txt
[[1;36mDEBUG[m] Scanning /org.springframework.samples.petclinic.service.ClinicServiceJdbcTests.txt
[[1;36mDEBUG[m] Scanning /org.springframework.samples.petclinic.service.ClinicServiceJpaTests.txt
[[1;36mDEBUG[m] Scanning /org.springframework.samples.petclinic.service.ClinicServiceSpringDataJpaTests.txt
[[1;36mDEBUG[m] Scanning /org.springframework.samples.petclinic.web.CrashControllerTests.txt
[[1;36mDEBUG[m] Scanning /org.springframework.samples.petclinic.web.OwnerControllerTests.txt
[[1;36mDEBUG[m] Scanning /org.springframework.samples.petclinic.web.PetControllerTests.txt
[[1;36mDEBUG[m] Scanning /org.springframework.samples.petclinic.web.PetTypeFormatterTests.txt
[[1;36mDEBUG[m] Scanning /org.springframework.samples.petclinic.web.VetControllerTests.txt
[[1;36mDEBUG[m] Scanning /org.springframework.samples.petclinic.web.VisitControllerTests.txt
[[1;36mDEBUG[m] Scanning /TEST-org.springframework.samples.petclinic.model.ValidatorTests.xml
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] [1;31mBUILD FAILURE[m
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] Total time: 02:00 min
[[1;34mINFO[m] Finished at: 2018-04-23T09:04:14+02:00
[[1;34mINFO[m] Final Memory: 47M/432M
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;31mERROR[m] Failed to execute goal [32mcom.buschmais.jqassistant:jqassistant-maven-plugin:1.3.0:scan[m [1m(default-cli)[m on project [36mspring-petclinic[m: [1;31mExecution default-cli of goal com.buschmais.jqassistant:jqassistant-maven-plugin:1.3.0:scan failed: Unexpected problem encountered while scanning: item='MavenProject: org.springframework.samples:spring-petclinic:4.2.6-SNAPSHOT @ C:\Temp\spring-petclinic\pom.xml', path='C:\Temp\spring-petclinic\pom.xml', scope='PROJECT', pipeline='[com.buschmais.jqassistant.plugin.maven3.impl.scanner.MavenProjectScannerPlugin@3397c8c0]'. Please report this error including the full stacktrace (continueOnError=false).[m: Unexpected problem encountered while scanning: item='C:\Temp\spring-petclinic\target\surefire-reports', path='C:\Temp\spring-petclinic\target/surefire-reports', scope='TESTREPORTS', pipeline='[com.buschmais.jqassistant.plugin.junit.impl.scanner.TestReportDirectoryScannerPlugin@482034fb]'. Please report this error including the full stacktrace (continueOnError=false). Unexpected problem encountered while scanning: item='C:\Temp\spring-petclinic\target\surefire-reports\TEST-org.springframework.samples.petclinic.model.ValidatorTests.xml', path='/TEST-org.springframework.samples.petclinic.model.ValidatorTests.xml', scope='TESTREPORTS', pipeline='[com.buschmais.jqassistant.plugin.common.impl.scanner.FileResourceScannerPlugin@769d0ef2, com.buschmais.jqassistant.plugin.junit.impl.scanner.TestReportScannerPlugin@57386162]'. Please report this error including the full stacktrace (continueOnError=false). Unexpected problem encountered while scanning: item='javax.xml.transform.stream.StreamSource@f905f3e', path='/TEST-org.springframework.samples.petclinic.model.ValidatorTests.xml', scope='TESTREPORTS', pipeline='[com.buschmais.jqassistant.plugin.xml.impl.scanner.XmlSourceScannerPlugin@2c2dfde3]'. Please report this error including the full stacktrace (continueOnError=false). NullPointerException -> [1m[Help 1][m
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal [32mcom.buschmais.jqassistant:jqassistant-maven-plugin:1.3.0:scan[m [1m(default-cli)[m on project [36mspring-petclinic[m: [1;31mExecution default-cli of goal com.buschmais.jqassistant:jqassistant-maven-plugin:1.3.0:scan failed: Unexpected problem encountered while scanning: item='MavenProject: org.springframework.samples:spring-petclinic:4.2.6-SNAPSHOT @ C:\Temp\spring-petclinic\pom.xml', path='C:\Temp\spring-petclinic\pom.xml', scope='PROJECT', pipeline='[com.buschmais.jqassistant.plugin.maven3.impl.scanner.MavenProjectScannerPlugin@3397c8c0]'. Please report this error including the full stacktrace (continueOnError=false).[m
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal com.buschmais.jqassistant:jqassistant-maven-plugin:1.3.0:scan failed: Unexpected problem encountered while scanning: item='MavenProject: org.springframework.samples:spring-petclinic:4.2.6-SNAPSHOT @ C:\Temp\spring-petclinic\pom.xml', path='C:\Temp\spring-petclinic\pom.xml', scope='PROJECT', pipeline='[com.buschmais.jqassistant.plugin.maven3.impl.scanner.MavenProjectScannerPlugin@3397c8c0]'. Please report this error including the full stacktrace (continueOnError=false).
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.IllegalStateException: Unexpected problem encountered while scanning: item='MavenProject: org.springframework.samples:spring-petclinic:4.2.6-SNAPSHOT @ C:\Temp\spring-petclinic\pom.xml', path='C:\Temp\spring-petclinic\pom.xml', scope='PROJECT', pipeline='[com.buschmais.jqassistant.plugin.maven3.impl.scanner.MavenProjectScannerPlugin@3397c8c0]'. Please report this error including the full stacktrace (continueOnError=false).
	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:93)
	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:59)
	at com.buschmais.jqassistant.scm.maven.ScanMojo.execute(ScanMojo.java:93)
	at com.buschmais.jqassistant.scm.maven.AbstractModuleMojo$1.run(AbstractModuleMojo.java:21)
	at com.buschmais.jqassistant.scm.maven.AbstractMojo.execute(AbstractMojo.java:326)
	at com.buschmais.jqassistant.scm.maven.AbstractModuleMojo.execute(AbstractModuleMojo.java:24)
	at com.buschmais.jqassistant.scm.maven.AbstractMojo.execute(AbstractMojo.java:211)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
Caused by: java.lang.IllegalStateException: Unexpected problem encountered while scanning: item='C:\Temp\spring-petclinic\target\surefire-reports', path='C:\Temp\spring-petclinic\target/surefire-reports', scope='TESTREPORTS', pipeline='[com.buschmais.jqassistant.plugin.junit.impl.scanner.TestReportDirectoryScannerPlugin@482034fb]'. Please report this error including the full stacktrace (continueOnError=false).
	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:93)
	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:59)
	at com.buschmais.jqassistant.plugin.maven3.impl.scanner.MavenProjectScannerPlugin.scanPath(MavenProjectScannerPlugin.java:328)
	at com.buschmais.jqassistant.plugin.maven3.impl.scanner.MavenProjectScannerPlugin.scanPath(MavenProjectScannerPlugin.java:299)
	at com.buschmais.jqassistant.plugin.maven3.impl.scanner.MavenProjectScannerPlugin.scan(MavenProjectScannerPlugin.java:94)
	at com.buschmais.jqassistant.plugin.maven3.impl.scanner.MavenProjectScannerPlugin.scan(MavenProjectScannerPlugin.java:39)
	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:82)
	... 28 more
Caused by: java.lang.IllegalStateException: Unexpected problem encountered while scanning: item='C:\Temp\spring-petclinic\target\surefire-reports\TEST-org.springframework.samples.petclinic.model.ValidatorTests.xml', path='/TEST-org.springframework.samples.petclinic.model.ValidatorTests.xml', scope='TESTREPORTS', pipeline='[com.buschmais.jqassistant.plugin.common.impl.scanner.FileResourceScannerPlugin@769d0ef2, com.buschmais.jqassistant.plugin.junit.impl.scanner.TestReportScannerPlugin@57386162]'. Please report this error including the full stacktrace (continueOnError=false).
	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:93)
	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:59)
	at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContainerScannerPlugin.scan(AbstractContainerScannerPlugin.java:50)
	at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContainerScannerPlugin.scan(AbstractContainerScannerPlugin.java:29)
	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:82)
	... 34 more
Caused by: java.lang.IllegalStateException: Unexpected problem encountered while scanning: item='javax.xml.transform.stream.StreamSource@f905f3e', path='/TEST-org.springframework.samples.petclinic.model.ValidatorTests.xml', scope='TESTREPORTS', pipeline='[com.buschmais.jqassistant.plugin.xml.impl.scanner.XmlSourceScannerPlugin@2c2dfde3]'. Please report this error including the full stacktrace (continueOnError=false).
	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:93)
	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:59)
	at com.buschmais.jqassistant.plugin.xml.api.scanner.AbstractXmlFileScannerPlugin.scan(AbstractXmlFileScannerPlugin.java:48)
	at com.buschmais.jqassistant.plugin.xml.api.scanner.AbstractXmlFileScannerPlugin.scan(AbstractXmlFileScannerPlugin.java:25)
	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:82)
	... 38 more
Caused by: java.lang.NullPointerException
	at com.buschmais.jqassistant.plugin.xml.impl.scanner.XmlSourceScannerPlugin.scan(XmlSourceScannerPlugin.java:63)
	at com.buschmais.jqassistant.plugin.xml.impl.scanner.XmlSourceScannerPlugin.scan(XmlSourceScannerPlugin.java:24)
	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:82)
	... 42 more
[[1;31mERROR[m] 
[[1;31mERROR[m] 
[[1;31mERROR[m] For more information about the errors and possible solutions, please read the following articles:
[[1;31mERROR[m] [1m[Help 1][m http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[[1;34mINFO[m] Closing store in directory 'bolt://localhost:7687'.
```

**Comment by DirkMahler** [comment]
Stupid thingy, the implementation of the scanner relies on a side effect of the underlying graph mapping framework (XO): there's a bidirectional relation between elements and their children, the scanner updates only one side but reads the other, will be fixed.

**Comment by DirkMahler** [comment]
Fixed and tested.

**Comment by feststelltaste** [comment]
Thanks, Dirk!
